# -*- coding: utf-8 -*-
"""Build TypeScript fragments from extracted_load_utf8.txt (manual-assisted parse)."""
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LOAD = ROOT / "tools/extracted_load_utf8.txt"


def main():
    raw = LOAD.read_text(encoding="utf-8")
    lines = [ln.strip() for ln in raw.splitlines()]

    # Teachers: блоки "Фамилия" + строка имени + строка отчества (кириллица)
    # Упрощённо ищем 3 строки подряд: паттерн фамилии, затем имя одно слово, затем отчество
    full_names = []
    i = 0
    while i < len(lines) - 2:
        a, b, c = lines[i], lines[i + 1], lines[i + 2]
        if (
            re.match(r"^[А-ЯЁ][а-яё\-]{1,40}$", a)
            and re.match(r"^[А-ЯЁ][а-яё\-]{1,40}$", b)
            and re.match(r"^[А-ЯЁ][а-яё\-]{1,60}$", c)
        ):
            # отсекаем технические строки типа «Радиофизика»
            tech = {"Радиофизика", "Фотоника", "Информатика", "Профилизация"}
            if (
                len(a.split()) == 1
                and len(b.split()) == 1
                and " " not in c
                and not a.startswith("ЛК")
                and not a.startswith("ЛБ")
            ):
                fname = f"{a} {b} {c}"
                if fname not in full_names:
                    full_names.append(fname)
        i += 1

    positions = []
    pos_kw = ("доцент", "преподаватель", "профессор", "асп.", "зав.кафедрой")
    for ln in lines:
        if any(k in ln.lower() for k in pos_kw) and len(ln) < 80:
            if ln not in positions:
                positions.append(ln)

    out_lines = []
    out_lines.append("// AUTO-GENERATED by tools/build_ts_from_extracts.py — do not hand-edit blindly")
    out_lines.append("export const EXTRACT_TEACHER_FULL_NAMES = [")
    for n in sorted(set(full_names), key=lambda x: x.split()[0]):
        out_lines.append(f"  {json_escape(n)!r},")
    out_lines.append("];")
    out_lines.append("")
    out_lines.append("export const EXTRACT_META_LINES = ")
    meta = "; ".join(sorted(set(lines[1:450])))[:0]  # skip
    print("Found", len(set(full_names)), "unique guessed full names")
    for sample in sorted(set(full_names))[:40]:
        print(" ", sample)
    (ROOT / "tools/_generated_preview.txt").write_text("\n".join(full_names[:200]), encoding="utf-8")


def json_escape(x: str) -> str:
    return x.replace("\\", "\\\\").replace("'", "\\'")


if __name__ == "__main__":
    main()
